# 介绍

NumPy(Numerical Python)是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。

NumPy 的前身 Numeric 最早是由 Jim Hugunin 与其它协作者共同开发，2005 年，Travis Oliphant 在 Numeric 中结合了另一个同性质的程序库 Numarray 的特色，并加入了其它扩展而开发了NumPy。NumPy开放源代码并且由许多协作者共同维护开发。

NumPy是一个运行速度非常快的数学库，主要用于数组计算，包含：
* 一个强大的N维数组对象 ndarray
* 广播功能函数
* 整合 C/C++/Fortran 代码的工具
* 线性代数、傅里叶变换、随机数生成等功能

在学习之前，首先得有python基础。由于numpy官网上面的教程已经很完善了，所以这里只是转移了教程的载体，并对排版进行了优化。

[官网在此](http://www.numpy.org/)

# Basic

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

[[ 1., 0., 0.],  
 [ 0., 1., 2.]]
 
NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

ndarray.ndim  
the number of axes (dimensions) of the array.

ndarray.shape  
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

ndarray.size  
the total number of elements of the array. This is equal to the product of the elements of shape.

ndarray.dtype  
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

ndarray.itemsize  
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

ndarray.data  
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.


In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int32'

In [5]:
a.itemsize

4

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

## Array Creation¶
There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [10]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [11]:
a.dtype

dtype('int32')

In [12]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [13]:
a = np.array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [14]:
a = np.array([1,2,3,4])  # RIGHT

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.



In [15]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

The type of the array can also be explicitly specified at creation time:



In [16]:
np.array( [ [1,2], [3,4] ], dtype=complex )

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [17]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [20]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [21]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:



In [22]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

## Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

* the last axis is printed from left to right,
* the second-to-last is printed from top to bottom,
* the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [26]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [27]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [29]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [30]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

```np.set_printoptions(threshold=np.nan)```

## Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.



In [31]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
c

array([20, 29, 38, 47])

In [32]:
b**2


array([0, 1, 4, 9], dtype=int32)

In [33]:
10*np.sin(a)


array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [34]:
a<35


array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:



In [35]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [36]:
A @ B                       # matrix product


array([[5, 4],
       [3, 4]])

In [37]:
A.dot(B)                    # another matrix product


array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.



In [38]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [39]:
b += a
b

array([[3.33584105, 3.20263912, 3.30156641],
       [3.50613264, 3.56773034, 3.93075864]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).



In [40]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [41]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [42]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [43]:
d.dtype.name


'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.



In [44]:
a = np.random.random((2,3))
a

array([[0.41358036, 0.0459122 , 0.03219523],
       [0.44255196, 0.73128501, 0.88353613]])

In [45]:
a.sum()

2.5490608896458395

In [46]:
a.min()

0.03219522686030085

In [47]:
a.max()

0.8835361336300354

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:



In [48]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [50]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [51]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.



In [52]:
B = np.arange(3)
B

array([0, 1, 2])

In [53]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [54]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [55]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

See also

all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

## Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.



In [56]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [57]:
a[2]

8

In [58]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [59]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [60]:
a[ : :-1]                                 # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [61]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


d:\Users\i9233\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:



In [70]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [63]:
b[2,3]

23

In [64]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [65]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [66]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:



In [71]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

* x[1,2,...] is equivalent to x[1,2,:,:,:],
* x[...,3] to x[:,:,:,:,3] and
* x[4,...,5,:] to x[4,:,:,5,:].

In [72]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape

(2, 2, 3)

In [73]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [74]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [75]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:



In [76]:
for element in b.flat:
    print(element)


0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
