# Changing the shape of an array
An array has a shape given by the number of elements along each axis:


In [2]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
a

array([[9., 6., 6., 0.],
       [1., 1., 4., 4.],
       [5., 8., 4., 2.]])

In [3]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:



In [4]:
a.ravel()  # returns the array, flattened

array([9., 6., 6., 0., 1., 1., 4., 4., 5., 8., 4., 2.])

In [5]:
a.reshape(6,2)  # returns the array with a modified shape

array([[9., 6.],
       [6., 0.],
       [1., 1.],
       [4., 4.],
       [5., 8.],
       [4., 2.]])

In [6]:
a.T  # returns the array, transposed

array([[9., 1., 5.],
       [6., 1., 8.],
       [6., 4., 4.],
       [0., 4., 2.]])

In [7]:
a.T.shape

(4, 3)

In [8]:
a.shape

(3, 4)

The order of the elements in the array resulting from ravel() is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the array is treated as “C-style”. NumPy normally creates arrays stored in this order, so ravel() will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions ravel() and reshape() can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [9]:
a

array([[9., 6., 6., 0.],
       [1., 1., 4., 4.],
       [5., 8., 4., 2.]])

In [10]:
a.resize((2,6))
a

array([[9., 6., 6., 0., 1., 1.],
       [4., 4., 5., 8., 4., 2.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:



In [11]:
a.reshape(3,-1)

array([[9., 6., 6., 0.],
       [1., 1., 4., 4.],
       [5., 8., 4., 2.]])

# Stacking together different arrays

Several arrays can be stacked together along different axes:



In [12]:
a = np.floor(10*np.random.random((2,2)))
a

array([[3., 3.],
       [4., 2.]])

In [13]:
b = np.floor(10*np.random.random((2,2)))
b

array([[3., 4.],
       [8., 2.]])

In [14]:
np.vstack((a,b))

array([[3., 3.],
       [4., 2.],
       [3., 4.],
       [8., 2.]])

In [15]:
np.hstack((a,b))

array([[3., 3., 3., 4.],
       [4., 2., 8., 2.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:



In [16]:
from numpy import newaxis
np.column_stack((a,b))     # with 2D arrays

array([[3., 3., 3., 4.],
       [4., 2., 8., 2.]])

In [17]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [18]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [19]:
a[:,newaxis]               # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [20]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [21]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

On the other hand, the function row_stack is equivalent to vstack for any input arrays. In general, for arrays of with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

## Note
In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals (“:”)



In [22]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

When used with arrays as arguments, r_ and c_ are similar to vstack and hstack in their default behavior, but allow for an optional argument giving the number of the axis along which to concatenate.



# Splitting one array into several smaller ones
Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [23]:
a = np.floor(10*np.random.random((2,12)))
a

array([[7., 5., 4., 3., 6., 5., 5., 9., 7., 3., 6., 5.],
       [6., 0., 7., 8., 6., 6., 5., 5., 9., 5., 1., 9.]])

In [24]:
np.hsplit(a,3)   # Split a into 3

[array([[7., 5., 4., 3.],
        [6., 0., 7., 8.]]), array([[6., 5., 5., 9.],
        [6., 6., 5., 5.]]), array([[7., 3., 6., 5.],
        [9., 5., 1., 9.]])]

In [25]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[7., 5., 4.],
        [6., 0., 7.]]), array([[3.],
        [8.]]), array([[6., 5., 5., 9., 7., 3., 6., 5.],
        [6., 6., 5., 5., 9., 5., 1., 9.]])]